/**
 * JLPT Grammar Pattern Detector (TypeScript port of jlpt_sentence_parser.py)
 *
 * Detects N5–N2 grammar patterns in Japanese sentences using regex.
 * Grammar IDs match masterGrammars.json / the grammar_id column in master_grammar.
 *
 * Usage:
 *   import { detect } from './grammarParser';
 *   const grammarIds = detect("日本語を勉強しなければならない");
 */

type PatternEntry = {
  pattern: RegExp;
  grammar_point: string;
  meaning: string;
};

// Keys are global grammar_ids matching masterGrammars.json
const ALL_PATTERNS: Record<number, PatternEntry> = {

  // ── N5 ──────────────────────────────────────────────────────────────────
  0:  { pattern: /(ちゃいけない|じゃいけない)/, grammar_point: "ちゃいけない・じゃいけない", meaning: "must not do (spoken Japanese)" },
  3:  { pattern: /だろう/, grammar_point: "だろう", meaning: "I think; it seems; probably; right?" },
  6:  { pattern: /でしょう/, grammar_point: "でしょう", meaning: "I think; it seems; probably; right?" },
  7:  { pattern: /どんな/, grammar_point: "どんな", meaning: "what kind of; what sort of" },
  8:  { pattern: /どうして/, grammar_point: "どうして", meaning: "why; for what reason; how" },
  9:  { pattern: /どうやって/, grammar_point: "どうやって", meaning: "how; in what way; by what means" },
  11: { pattern: /(がある|があります)/, grammar_point: "があります", meaning: "there is; is (non-living things)" },
  12: { pattern: /が(ほしい|欲しい)/, grammar_point: "がほしい", meaning: "to want something" },
  13: { pattern: /(がいる|がいます)/, grammar_point: "がいます", meaning: "there is; to be; is (living things)" },
  14: { pattern: /(ほう|方)が(いい|良い)/, grammar_point: "ほうがいい", meaning: "had better; it'd be better to; should~" },
  15: { pattern: /(いちばん|一番)/, grammar_point: "いちばん", meaning: "the most; the best" },
  16: { pattern: /(いっしょに|一緒に)/, grammar_point: "いっしょに", meaning: "together" },
  17: { pattern: /いつも/, grammar_point: "いつも", meaning: "always; usually; habitually" },
  18: { pattern: /(じゃない|ではない)/, grammar_point: "じゃない・ではない", meaning: "to not be (am not; is not; are not)" },
  24: { pattern: /けれども/, grammar_point: "けれども", meaning: "but; however; although" },
  26: { pattern: /まだ.+て(いません|ない)/, grammar_point: "まだ〜ていません", meaning: "have not yet" },
  28: { pattern: /(前に|まえに)/, grammar_point: "前に", meaning: "before ~; in front of ~" },
  29: { pattern: /ませんか/, grammar_point: "ませんか", meaning: "would you; do you want to; shall we~" },
  30: { pattern: /ましょう(?!か)/, grammar_point: "ましょう", meaning: "let's ~; shall we ~" },
  31: { pattern: /ましょうか/, grammar_point: "ましょうか", meaning: "shall I ~; used to offer help" },
  35: { pattern: /ないで(?!ください)/, grammar_point: "ないで", meaning: "without doing~" },
  36: { pattern: /ないでください/, grammar_point: "ないでください", meaning: "please don't do" },
  37: { pattern: /なくてもいい/, grammar_point: "なくてもいい", meaning: "don't have to" },
  38: { pattern: /なくちゃ/, grammar_point: "なくちゃ", meaning: "must do; need to; gotta do" },
  39: { pattern: /なくてはいけない/, grammar_point: "なくてはいけない", meaning: "must do; need to do" },
  40: { pattern: /なくてはならない/, grammar_point: "なくてはならない", meaning: "must do; need to do" },
  42: { pattern: /(んです|んだ)/, grammar_point: "んです", meaning: "to explain something; show emphasis" },
  49: { pattern: /(のです|のだ)/, grammar_point: "のです", meaning: "to explain something; show emphasis" },
  50: { pattern: /のが(へた|下手)/, grammar_point: "のがへた", meaning: "to be bad at doing something" },
  51: { pattern: /のが(じょうず|上手)/, grammar_point: "のがじょうず", meaning: "to be good at" },
  52: { pattern: /のが(すき|好き)/, grammar_point: "のが好き", meaning: "to like doing something" },
  55: { pattern: /をください/, grammar_point: "をください", meaning: "please give me~" },
  56: { pattern: /(?<!も)しかし/, grammar_point: "しかし", meaning: "but; however" },
  57: { pattern: /(すぎる|過ぎる)/, grammar_point: "すぎる", meaning: "too much" },
  58: { pattern: /たことが(ある|あります)/, grammar_point: "たことがある", meaning: "to have done something before" },
  60: { pattern: /たり.+たり/, grammar_point: "たり〜たり", meaning: "do such things as A and B" },
  61: { pattern: /てある/, grammar_point: "てある", meaning: "is/has been done (resulting state)" },
  62: { pattern: /(ている|てる)/, grammar_point: "ている", meaning: "ongoing action or current state" },
  63: { pattern: /てから/, grammar_point: "てから", meaning: "after doing~" },
  64: { pattern: /てください/, grammar_point: "てください", meaning: "please do" },
  65: { pattern: /てはいけない/, grammar_point: "てはいけない", meaning: "must not; may not; cannot" },
  66: { pattern: /てもいい/, grammar_point: "てもいいです", meaning: "is OK to..; is alright to..; may I..?" },
  69: { pattern: /とても/, grammar_point: "とても", meaning: "very; awfully; exceedingly" },
  70: { pattern: /つもり/, grammar_point: "つもり", meaning: "plan to ~; intend to ~" },
  72: { pattern: /は.+より.+です/, grammar_point: "は〜より・・・です", meaning: "[A] is more ~ than [B]" },
  73: { pattern: /はどうですか/, grammar_point: "はどうですか", meaning: "how about; how is" },
  76: { pattern: /より.+(ほう|方)が/, grammar_point: "より〜ほうが", meaning: "[A] is more than [B]" },

  // ── N4 ──────────────────────────────────────────────────────────────────
  78:  { pattern: /間に/, grammar_point: "間に", meaning: "while/during~ something happened" },
  79:  { pattern: /あまり.+(ない|ません)/, grammar_point: "あまり〜ない", meaning: "not very; not much" },
  80:  { pattern: /(後で|あとで)/, grammar_point: "後で", meaning: "after ~; later" },
  82:  { pattern: /場合/, grammar_point: "場合は", meaning: "in the event of; in the case that" },
  83:  { pattern: /ばかり/, grammar_point: "ばかり", meaning: "only; nothing but" },
  84:  { pattern: /だけで/, grammar_point: "だけで", meaning: "just by; just by doing" },
  86:  { pattern: /でございます/, grammar_point: "でございます", meaning: "to be (honorific)" },
  88:  { pattern: /ではないか/, grammar_point: "ではないか", meaning: "right?; isn't it?" },
  89:  { pattern: /が必要/, grammar_point: "が必要", meaning: "need; necessary" },
  92:  { pattern: /(がる|がっている)/, grammar_point: "がる・がっている", meaning: "to show signs of; to appear; to feel" },
  93:  { pattern: /ございます/, grammar_point: "ございます", meaning: "to be; to exist (polite form)" },
  95:  { pattern: /はず(だ|です)/, grammar_point: "はずだ", meaning: "it must be; it should be (expectation)" },
  96:  { pattern: /はずがない/, grammar_point: "はずがない", meaning: "cannot be (impossible)" },
  97:  { pattern: /必要がある/, grammar_point: "必要がある", meaning: "need to; it is necessary to" },
  99:  { pattern: /(いらっしゃる|いらっしゃい)/, grammar_point: "いらっしゃる", meaning: "to be; to come; to go (polite)" },
  100: { pattern: /(いたします|いたす)/, grammar_point: "いたします", meaning: "to do (polite form of する)" },
  101: { pattern: /じゃないか/, grammar_point: "じゃないか", meaning: "right? isn't it? let's~" },
  102: { pattern: /かどうか/, grammar_point: "かどうか", meaning: "whether or not" },
  103: { pattern: /かしら/, grammar_point: "かしら", meaning: "I wonder" },
  105: { pattern: /かもしれない|かもしれません/, grammar_point: "かもしれない", meaning: "might; perhaps; indicates possibility" },
  107: { pattern: /から(作る|つくる)/, grammar_point: "から作る", meaning: "made from; made with" },
  108: { pattern: /きっと/, grammar_point: "きっと", meaning: "surely; undoubtedly; almost certainly" },
  110: { pattern: /ことがある/, grammar_point: "ことがある", meaning: "there are times when" },
  111: { pattern: /ことができる/, grammar_point: "ことができる", meaning: "can; able to" },
  112: { pattern: /ことになる/, grammar_point: "ことになる", meaning: "It has been decided that..; it turns out that.." },
  113: { pattern: /ことにする/, grammar_point: "ことにする", meaning: "to decide on" },
  115: { pattern: /急に/, grammar_point: "急に", meaning: "suddenly" },
  116: { pattern: /までに/, grammar_point: "までに", meaning: "by; by the time; indicates time limit" },
  118: { pattern: /または/, grammar_point: "または", meaning: "both; or; otherwise" },
  119: { pattern: /みたい(だ|です)/, grammar_point: "みたいだ", meaning: "like; similar to; resembling" },
  120: { pattern: /みたいな/, grammar_point: "みたいな", meaning: "like; similar to" },
  121: { pattern: /みたいに/, grammar_point: "みたいに", meaning: "like; similar to" },
  125: { pattern: /ながら/, grammar_point: "ながら", meaning: "while; during; as; simultaneously" },
  126: { pattern: /なかなか.+(ない|ません)/, grammar_point: "なかなか〜ない", meaning: "not easy to; struggling to; not able to~" },
  127: { pattern: /なければいけない/, grammar_point: "なければいけない", meaning: "must do something; have to do something" },
  128: { pattern: /なければならない/, grammar_point: "なければならない", meaning: "must do something; have to do something" },
  130: { pattern: /なさい/, grammar_point: "なさい", meaning: "do this (soft/firm command)" },
  131: { pattern: /なさる/, grammar_point: "なさる", meaning: "to do (honorific)" },
  132: { pattern: /に(気がつく|気づく)/, grammar_point: "に気がつく", meaning: "to notice; to realize" },
  133: { pattern: /に(みえる|見える)/, grammar_point: "にみえる", meaning: "to look; to seem; to appear" },
  135: { pattern: /にくい/, grammar_point: "にくい", meaning: "difficult to do" },
  136: { pattern: /の中で/, grammar_point: "の中で", meaning: "in; among" },
  138: { pattern: /のは.+(だ|です)/, grammar_point: "のは〜だ", meaning: "[A] is [B]; the reason for [A] is [B]" },
  139: { pattern: /お.+ください/, grammar_point: "お〜ください", meaning: "please do (honorific)" },
  140: { pattern: /お.+になる/, grammar_point: "お〜になる", meaning: "to do (honorific)" },
  141: { pattern: /おきに/, grammar_point: "おきに", meaning: "repeated at intervals; every" },
  144: { pattern: /らしい/, grammar_point: "らしい", meaning: "it seems like; I heard; apparently~" },
  146: { pattern: /さっき/, grammar_point: "さっき", meaning: "some time ago; just now" },
  147: { pattern: /させられる/, grammar_point: "させられる", meaning: "causative-passive; to be made to do" },
  148: { pattern: /させる/, grammar_point: "させる", meaning: "causative form; to make/let somebody do" },
  149: { pattern: /させてください/, grammar_point: "させてください", meaning: "please let me do" },
  150: { pattern: /さすが/, grammar_point: "さすが", meaning: "as one would expect; as is to be expected" },
  152: { pattern: /そんなに/, grammar_point: "そんなに", meaning: "so much; so; like that" },
  153: { pattern: /それでも/, grammar_point: "それでも", meaning: "but still; and yet; even so" },
  155: { pattern: /(そうに|そうな)/, grammar_point: "そうに・そうな", meaning: "seems like; looks like" },
  156: { pattern: /たばかり/, grammar_point: "たばかり", meaning: "just finished; something just occurred" },
  157: { pattern: /たところ/, grammar_point: "たところ", meaning: "just finished doing; was just doing" },
  158: { pattern: /(たがる|たがっている)/, grammar_point: "たがる", meaning: "wants to do~ (third person)" },
  160: { pattern: /たらどう/, grammar_point: "たらどう", meaning: "why don't you" },
  161: { pattern: /たらいいですか/, grammar_point: "たらいいですか", meaning: "what should I do?; speaker seeking" },
  163: { pattern: /てあげる/, grammar_point: "てあげる", meaning: "to do for; to do a favor" },
  164: { pattern: /て(ほしい|欲しい)/, grammar_point: "てほしい", meaning: "I want you to; need you to~" },
  165: { pattern: /て(いく|行く)/, grammar_point: "ていく", meaning: "to start; to continue; to go on" },
  166: { pattern: /ていた/, grammar_point: "ていた", meaning: "was doing something (past continuous)" },
  167: { pattern: /ていただけませんか/, grammar_point: "ていただけませんか", meaning: "could you please" },
  168: { pattern: /てくれる/, grammar_point: "てくれる", meaning: "to do a favor; do something for someone" },
  169: { pattern: /て(くる|来る)/, grammar_point: "てくる", meaning: "to do… and come back; to become" },
  170: { pattern: /てみる/, grammar_point: "てみる", meaning: "try doing" },
  171: { pattern: /てもらう/, grammar_point: "てもらう", meaning: "to get somebody to do something" },
  172: { pattern: /ておく/, grammar_point: "ておく", meaning: "to do something in advance" },
  173: { pattern: /(てしまう|ちゃう|じゃう)/, grammar_point: "てしまう・ちゃう", meaning: "to do something by accident; to finish" },
  174: { pattern: /てすみません/, grammar_point: "てすみません", meaning: "I'm sorry for" },
  175: { pattern: /てやる/, grammar_point: "てやる", meaning: "to do for; to do a favor (casual)" },
  176: { pattern: /てよかった/, grammar_point: "てよかった", meaning: "I'm glad that.." },
  177: { pattern: /ているところ/, grammar_point: "ているところ", meaning: "in the process of doing" },
  180: { pattern: /と(いっても|言っても)いい/, grammar_point: "といってもいい", meaning: "you could say; one might say; I'd say" },
  181: { pattern: /という/, grammar_point: "という", meaning: "called; named; that" },
  182: { pattern: /ということ/, grammar_point: "ということ", meaning: "convert phrase into noun" },
  183: { pattern: /と(いわれている|言われている)/, grammar_point: "といわれている", meaning: "it is said that..." },
  184: { pattern: /と聞いた/, grammar_point: "と聞いた", meaning: "I heard..." },
  185: { pattern: /と思う/, grammar_point: "と思う", meaning: "to think…; I think…; you think…" },
  186: { pattern: /とか.+とか/, grammar_point: "とか〜とか", meaning: "among other things; such as; like" },
  188: { pattern: /続ける/, grammar_point: "続ける", meaning: "continue to; keen on" },
  192: { pattern: /やすい/, grammar_point: "やすい", meaning: "easy to; likely to; prone to" },
  193: { pattern: /やっと/, grammar_point: "やっと", meaning: "at last; finally; barely; narrowly" },
  195: { pattern: /予定(だ|です)/, grammar_point: "予定だ", meaning: "plan to; intend to" },
  197: { pattern: /(ように|ような)/, grammar_point: "ように・ような", meaning: "like; as; similar to" },
  198: { pattern: /ようになる/, grammar_point: "ようになる", meaning: "to reach the point that; to come to be that" },
  199: { pattern: /ようにする/, grammar_point: "ようにする", meaning: "to try to; to make sure that" },
  200: { pattern: /ようと思う/, grammar_point: "ようと思う", meaning: "thinking of doing; planning to" },
  201: { pattern: /ぜひ/, grammar_point: "ぜひ", meaning: "by all means; certainly; definitely" },
  202: { pattern: /全然.+(ない|ません)/, grammar_point: "全然〜ない", meaning: "(not) at all" },
  203: { pattern: /づらい/, grammar_point: "づらい", meaning: "difficult to do" },

  // ── N3 ──────────────────────────────────────────────────────────────────
  206: { pattern: /あまりにも/, grammar_point: "あまりにも", meaning: "too much; so much… that; excessively~" },
  208: { pattern: /ばいい/, grammar_point: "ばいい", meaning: "should; can; it'd be good if" },
  209: { pattern: /ばよかった/, grammar_point: "ばよかった", meaning: "should have; would have been better if~" },
  210: { pattern: /ば.+ほど/, grammar_point: "ば〜ほど", meaning: "the more… the more" },
  211: { pattern: /ば.+のに/, grammar_point: "ば〜のに", meaning: "would have; should have; if only~" },
  212: { pattern: /ばかりで(?!なく)/, grammar_point: "ばかりで", meaning: "only; just (negative description)" },
  213: { pattern: /ばかりでなく/, grammar_point: "ばかりでなく", meaning: "not only.. but also; as well as~" },
  214: { pattern: /べき(だ|です)(?!ではない)/, grammar_point: "べきだ", meaning: "should do~; must do~" },
  215: { pattern: /べきではない/, grammar_point: "べきではない", meaning: "should not do~; must not do~" },
  216: { pattern: /別に.+(ない|ません)/, grammar_point: "別に〜ない", meaning: "not really; not particularly" },
  217: { pattern: /ぶりに/, grammar_point: "ぶりに", meaning: "for the first time in (period of time)" },
  220: { pattern: /だけでなく/, grammar_point: "だけでなく", meaning: "not only… but also" },
  221: { pattern: /だけど/, grammar_point: "だけど", meaning: "however; but" },
  222: { pattern: /だらけ/, grammar_point: "だらけ", meaning: "full of; covered with; a lot of" },
  223: { pattern: /どんなに.+ても/, grammar_point: "どんなに〜ても", meaning: "no matter how (much)" },
  224: { pattern: /どうしても/, grammar_point: "どうしても", meaning: "no matter what; at any cost; after all" },
  225: { pattern: /ふりを(する|して)/, grammar_point: "ふりをする", meaning: "to pretend; to act as if~" },
  228: { pattern: /がたい/, grammar_point: "がたい", meaning: "very difficult to; impossible to" },
  229: { pattern: /気味/, grammar_point: "気味", meaning: "-like; -looking; tending to" },
  230: { pattern: /ごとに/, grammar_point: "ごとに", meaning: "each; every; at intervals of" },
  232: { pattern: /ほど.+(ない|ません)/, grammar_point: "ほど〜ない", meaning: "is not as… as" },
  233: { pattern: /(一度に|いちどに)/, grammar_point: "いちどに", meaning: "all at once" },
  234: { pattern: /いくら.+ても/, grammar_point: "いくら〜ても", meaning: "no matter how~" },
  235: { pattern: /(一方だ|いっぽうだ)/, grammar_point: "いっぽうだ", meaning: "more and more; continue to" },
  236: { pattern: /(一体|いったい)/, grammar_point: "いったい", meaning: "emphasis; what on earth; what in the" },
  238: { pattern: /か何か/, grammar_point: "か何か", meaning: "or something" },
  240: { pattern: /から.+にかけて/, grammar_point: "から〜にかけて", meaning: "through; from [A] to [B]" },
  241: { pattern: /(代わりに|かわりに)/, grammar_point: "代わりに", meaning: "instead of; as a substitute for" },
  243: { pattern: /結局/, grammar_point: "結局", meaning: "after all; eventually; in the end" },
  244: { pattern: /決して.+(ない|ません)/, grammar_point: "決して〜ない", meaning: "never; by no means" },
  245: { pattern: /切れない/, grammar_point: "切れない", meaning: "unable to do; too much to finish/complete" },
  252: { pattern: /ことから/, grammar_point: "ことから", meaning: "from the fact that~" },
  253: { pattern: /ことになっている/, grammar_point: "ことになっている", meaning: "to be expected to; to be scheduled to" },
  254: { pattern: /ことはない/, grammar_point: "ことはない", meaning: "there is no need to; (something) never" },
  255: { pattern: /ことは.+が/, grammar_point: "ことは〜が", meaning: "although; but" },
  257: { pattern: /くせに/, grammar_point: "くせに", meaning: "although~; despite the fact that~" },
  258: { pattern: /まるで/, grammar_point: "まるで", meaning: "as if; as though; just like" },
  259: { pattern: /まさか/, grammar_point: "まさか", meaning: "there's no way; that's impossible" },
  260: { pattern: /めったに.+(ない|ません)/, grammar_point: "めったに〜ない", meaning: "hardly; rarely; seldom" },
  261: { pattern: /も.+ば.+も/, grammar_point: "も〜ば〜も", meaning: "and; also; as well; either/or; neither/nor" },
  262: { pattern: /もしかしたら/, grammar_point: "もしかしたら", meaning: "perhaps; maybe; perchance; by any chance" },
  263: { pattern: /もしも.+たら/, grammar_point: "もしも〜たら", meaning: "if; in the case; supposing~" },
  266: { pattern: /むしろ/, grammar_point: "むしろ", meaning: "rather; instead; better" },
  267: { pattern: /ながらも/, grammar_point: "ながらも", meaning: "but; although; despite" },
  268: { pattern: /ないことはない/, grammar_point: "ないことはない", meaning: "can do~; is not impossible to~" },
  270: { pattern: /なかなか/, grammar_point: "なかなか", meaning: "quite~; pretty~; rather~; just not ~" },
  273: { pattern: /なるべく/, grammar_point: "なるべく", meaning: "as much as possible" },
  274: { pattern: /なぜなら/, grammar_point: "なぜなら", meaning: "because; the reason is" },
  275: { pattern: /んだって/, grammar_point: "んだって", meaning: "I hear that; heard that~" },
  276: { pattern: /に違いない/, grammar_point: "に違いない", meaning: "I'm sure/certain; no doubt that" },
  277: { pattern: /に反して/, grammar_point: "に反して", meaning: "against; contrary to; in contrast to" },
  278: { pattern: /にかけて/, grammar_point: "にかけて", meaning: "over (a period); through~; concerning~" },
  279: { pattern: /に(かわって|かわり|代わって|代わり)/, grammar_point: "にかわって・にかわり", meaning: "instead of~; replacing~; on behalf of~" },
  280: { pattern: /に(くらべて|比べて)/, grammar_point: "にくらべて", meaning: "compared to~; in comparison to~" },
  281: { pattern: /に(慣れ|なれ)/, grammar_point: "に慣れる", meaning: "to be used to something" },
  282: { pattern: /(において|における)/, grammar_point: "において・における", meaning: "in; at (place); regarding~; as for~" },
  283: { pattern: /に(したがって|従って)/, grammar_point: "にしたがって", meaning: "as; therefore; in accordance with" },
  284: { pattern: /にしても/, grammar_point: "にしても", meaning: "even if; even though; regardless of" },
  285: { pattern: /にしては/, grammar_point: "にしては", meaning: "for; considering it's" },
  286: { pattern: /に対して/, grammar_point: "に対して", meaning: "towards; against; regarding; in contrast with" },
  287: { pattern: /にとって/, grammar_point: "にとって", meaning: "to; for; concerning; as far as ... is concerned" },
  288: { pattern: /について/, grammar_point: "について", meaning: "concerning; regarding; about; on" },
  289: { pattern: /につれて/, grammar_point: "につれて", meaning: "as; in proportion to; with; as… then…" },
  291: { pattern: /(によると|によれば)/, grammar_point: "によると・によれば", meaning: "according to~" },
  292: { pattern: /(によって|による)/, grammar_point: "によって・による", meaning: "by means of; due to; owing to; because of~" },
  293: { pattern: /のでしょうか/, grammar_point: "のでしょうか", meaning: "ask a question in a polite way" },
  294: { pattern: /を(中心に|ちゅうしんに)/, grammar_point: "をちゅうしんに", meaning: "focused on; centered on" },
  295: { pattern: /をはじめ/, grammar_point: "をはじめ", meaning: "for example; starting with" },
  296: { pattern: /を込めて/, grammar_point: "を込めて", meaning: "filled with; full of" },
  297: { pattern: /おかげで/, grammar_point: "おかげで", meaning: "thanks to ...; owing to ...; because of ..." },
  298: { pattern: /っぱなし/, grammar_point: "っぱなし", meaning: "leaving (something) on; leaving (something)" },
  299: { pattern: /っぽい/, grammar_point: "っぽい", meaning: "seems like; somewhat~; -ish; easily does~" },
  301: { pattern: /さえ.+ば/, grammar_point: "さえ〜ば", meaning: "if only; as long as" },
  302: { pattern: /際に/, grammar_point: "際に", meaning: "when; at the time of; in the case of" },
  303: { pattern: /最中に/, grammar_point: "最中に", meaning: "while; during; in the middle of" },
  304: { pattern: /さらに/, grammar_point: "さらに", meaning: "furthermore; again; more and more" },
  306: { pattern: /せいで/, grammar_point: "せいで", meaning: "because of; due to; as a result of~" },
  307: { pattern: /せいぜい/, grammar_point: "せいぜい", meaning: "at the most; at best; to the utmost" },
  308: { pattern: /しばらく/, grammar_point: "しばらく", meaning: "for a moment; for a while; for the time being" },
  309: { pattern: /しかない/, grammar_point: "しかない", meaning: "have no choice but~" },
  310: { pattern: /そのため(に)?/, grammar_point: "そのために", meaning: "hence; for that reason; because of~" },
  311: { pattern: /それとも/, grammar_point: "それとも", meaning: "or; or else" },
  312: { pattern: /(そうもない|そうにない)/, grammar_point: "そうもない・そうにない", meaning: "very unlikely to~; showing no signs of~" },
  313: { pattern: /すでに/, grammar_point: "すでに", meaning: "something has already been done/taken" },
  314: { pattern: /すなわち/, grammar_point: "すなわち", meaning: "in other words; namely" },
  315: { pattern: /たものだ/, grammar_point: "たものだ", meaning: "used to do; would often do" },
  316: { pattern: /(たとたん|た途端)/, grammar_point: "たとたん", meaning: "as soon as; just as" },
  317: { pattern: /たびに/, grammar_point: "たびに", meaning: "whenever; every time" },
  319: { pattern: /確かに/, grammar_point: "確かに", meaning: "surely; certainly" },
  321: { pattern: /たとえ.+ても/, grammar_point: "たとえ〜ても", meaning: "even if… is the case" },
  322: { pattern: /(例えば|たとえば)/, grammar_point: "例えば", meaning: "for example" },
  324: { pattern: /てばかりいる/, grammar_point: "てばかりいる", meaning: "only; nothing but~" },
  325: { pattern: /てごらん/, grammar_point: "てごらん", meaning: "(please) try to; (please) look" },
  326: { pattern: /て(はじめて|初めて)/, grammar_point: "てはじめて", meaning: "not until; only after [x] did I" },
  327: { pattern: /てからでないと/, grammar_point: "てからでないと", meaning: "must first do; cannot do without first doing" },
  328: { pattern: /(てしょうがない|てしかたがない|て仕方がない)/, grammar_point: "てしょうがない・てしかたがない", meaning: "can't help but~; very; extremely" },
  329: { pattern: /て済む/, grammar_point: "て済む", meaning: "sufficient by; no problem to; resolve by~" },
  330: { pattern: /てはいけないから/, grammar_point: "てはいけないから", meaning: "in order to not~; to prevent a negative" },
  331: { pattern: /ている場合じゃない/, grammar_point: "ている場合じゃない", meaning: "this is no time to be doing~" },
  333: { pattern: /ても始まらない/, grammar_point: "ても始まらない", meaning: "even if you... it's no use; there is no point" },
  334: { pattern: /(てもかまわない|ても構わない)/, grammar_point: "てもかまわない", meaning: "it doesn't matter if ~" },
  335: { pattern: /(てもしょうがない|てもしかたがない)/, grammar_point: "てもしょうがない・てもしかたがない", meaning: "there's no point to~; it's no use to~" },
  336: { pattern: /(といえば|と言えば)/, grammar_point: "といえば", meaning: "speaking of; when you talk of; when you say" },
  337: { pattern: /(といい|たらいい)/, grammar_point: "といい・たらいい", meaning: "it would be nice if; should; I hope~" },
  338: { pattern: /(といっても|と言っても)/, grammar_point: "といっても", meaning: "although I say; although one might say~" },
  339: { pattern: /ということだ/, grammar_point: "ということだ", meaning: "I heard~; it means that~; in other words~" },
  340: { pattern: /というのは/, grammar_point: "というのは", meaning: "this means~; the meaning of … is~" },
  341: { pattern: /というと/, grammar_point: "というと", meaning: "speaking of; when you talk of" },
  342: { pattern: /というより/, grammar_point: "というより", meaning: "rather than~" },
  343: { pattern: /と(みえる|みえて|見える|見えて)/, grammar_point: "とみえる・とみえて", meaning: "it seems that~" },
  344: { pattern: /(とすれば|としたら|とすると)/, grammar_point: "とすれば・としたら・とすると", meaning: "in the case of~; assuming~; if A then B" },
  345: { pattern: /(と共に|とともに)/, grammar_point: "と共に", meaning: "together with; at the same time as; as well" },
  346: { pattern: /ところで/, grammar_point: "ところで", meaning: "by the way~" },
  347: { pattern: /ところが/, grammar_point: "ところが", meaning: "even so; however; even though~" },
  348: { pattern: /(とおりに|通りに)/, grammar_point: "とおりに", meaning: "in the same way as; in the way; as~" },
  350: { pattern: /として/, grammar_point: "として", meaning: "as~; in the role of~" },
  351: { pattern: /とても.+(ない|ません)/, grammar_point: "とても〜ない", meaning: "cannot possibly be; hardly~" },
  352: { pattern: /とは限らない/, grammar_point: "とは限らない", meaning: "not necessarily so; is not always true" },
  354: { pattern: /ついに/, grammar_point: "ついに", meaning: "finally ~; at last ~; in the end" },
  355: { pattern: /ついでに/, grammar_point: "ついでに", meaning: "while; incidentally; at the same time" },
  356: { pattern: /つまり/, grammar_point: "つまり", meaning: "in other words; in summary; in short" },
  357: { pattern: /つもりだった/, grammar_point: "つもりだった", meaning: "I thought I~; I believe I~; was planning to~" },
  358: { pattern: /つもりで/, grammar_point: "つもりで", meaning: "with the intention of doing~" },
  359: { pattern: /うちに/, grammar_point: "うちに", meaning: "while; before~" },
  360: { pattern: /上で/, grammar_point: "上で", meaning: "upon; after; when; for; in order to" },
  361: { pattern: /上に/, grammar_point: "上に", meaning: "as well; besides; in addition to; not only…" },
  362: { pattern: /は別として/, grammar_point: "は別として", meaning: "aside from; apart from; except for" },
  363: { pattern: /はもちろん/, grammar_point: "はもちろん", meaning: "not to mention; not only; but also~" },
  364: { pattern: /は.+で有名/, grammar_point: "は〜で有名", meaning: "famous for~" },
  365: { pattern: /わけ(だ|です)/, grammar_point: "わけだ", meaning: "for that reason; no wonder; as you'd expect" },
  366: { pattern: /わけではない/, grammar_point: "わけではない", meaning: "it doesn't mean that; it is not the case that" },
  367: { pattern: /わけがない/, grammar_point: "わけがない", meaning: "there is no way that~; it is impossible to~" },
  368: { pattern: /わけにはいかない/, grammar_point: "わけにはいかない", meaning: "must not; cannot afford to; must" },
  369: { pattern: /割に/, grammar_point: "割に", meaning: "considering; comparatively; relatively" },
  370: { pattern: /わざと/, grammar_point: "わざと", meaning: "on purpose; intentionally~" },
  371: { pattern: /わざわざ/, grammar_point: "わざわざ", meaning: "to go to the trouble of; to go out of one's way" },
  372: { pattern: /よりも/, grammar_point: "よりも", meaning: "in comparison to; rather than~; more than~" },
  373: { pattern: /ようがない/, grammar_point: "ようがない", meaning: "there is no way to; it's impossible to~" },
  374: { pattern: /ような気がする/, grammar_point: "ような気がする", meaning: "have a feeling that; feels like; seems like" },
  376: { pattern: /ように(みえる|見える)/, grammar_point: "ようにみえる", meaning: "to look; to seem; to appear~" },
  377: { pattern: /ようとしない/, grammar_point: "ようとしない", meaning: "not try to; not make an effort to~" },
  378: { pattern: /ようとする/, grammar_point: "ようとする", meaning: "try to; attempt to; be about to~" },
  379: { pattern: /ずに/, grammar_point: "ずに", meaning: "without doing~" },
  380: { pattern: /ずにはいられない/, grammar_point: "ずにはいられない", meaning: "can't help but feel; can't help but do" },
  381: { pattern: /ずつ/, grammar_point: "ずつ", meaning: "apiece; each; at a time" },

  // ── N2 ──────────────────────────────────────────────────────────────────
  382: { pattern: /(あげく|挙げ句)/, grammar_point: "あげく", meaning: "to end up; in the end; finally; after all~" },
  383: { pattern: /あるいは/, grammar_point: "あるいは", meaning: "or; either; maybe; perhaps; possibly~" },
  385: { pattern: /ばかりだ/, grammar_point: "ばかりだ", meaning: "continue to (go in negative direction)" },
  386: { pattern: /ばかりか/, grammar_point: "ばかりか", meaning: "not only.. but also; as well as~" },
  387: { pattern: /ばかりに/, grammar_point: "ばかりに", meaning: "simply because; on account of~" },
  388: { pattern: /ちなみに/, grammar_point: "ちなみに", meaning: "by the way; in this connection; incidentally" },
  389: { pattern: /ちっとも.+(ない|ません)/, grammar_point: "ちっとも〜ない", meaning: "(not) at all; (not) in the least~" },
  390: { pattern: /だけあって/, grammar_point: "だけあって", meaning: "being the case; precisely because; as" },
  391: { pattern: /だけましだ/, grammar_point: "だけましだ", meaning: "it's better than; one should feel grateful for~" },
  392: { pattern: /だけに/, grammar_point: "だけに", meaning: "being the case; precisely because; as one" },
  393: { pattern: /だけのことはある/, grammar_point: "だけのことはある", meaning: "no wonder; as expected of; not ... for" },
  396: { pattern: /でしかない/, grammar_point: "でしかない", meaning: "merely; nothing but; no more than" },
  397: { pattern: /どころではない/, grammar_point: "どころではない", meaning: "not the time for; not the place for; far from" },
  398: { pattern: /どころか/, grammar_point: "どころか", meaning: "far from; anything but; let alone" },
  399: { pattern: /どうやら/, grammar_point: "どうやら", meaning: "possibly; apparently; seems like; somehow" },
  400: { pattern: /どうせ/, grammar_point: "どうせ", meaning: "anyhow; in any case; at any rate; after all" },
  401: { pattern: /(得ない|えない)/, grammar_point: "得ない", meaning: "unable to; cannot; it is not possible to~" },
  402: { pattern: /(再び|ふたたび)/, grammar_point: "再び", meaning: "again; once more" },
  404: { pattern: /(が|を)きっかけ(で|に)/, grammar_point: "がきっかけで・をきっかけに", meaning: "with… as a start; as a result of; taking" },
  406: { pattern: /逆に/, grammar_point: "逆に", meaning: "conversely; on the contrary~" },
  407: { pattern: /(反面|はんめん)/, grammar_point: "はんめん", meaning: "while; although; on the other hand~" },
  408: { pattern: /果たして/, grammar_point: "果たして", meaning: "as was expected; sure enough; really" },
  409: { pattern: /(一応|いちおう)/, grammar_point: "いちおう", meaning: "more or less; pretty much; roughly" },
  410: { pattern: /以外/, grammar_point: "以外", meaning: "with the exception of; excepting~" },
  411: { pattern: /以上に/, grammar_point: "以上に", meaning: "more than; not less than; beyond~" },
  412: { pattern: /以上は/, grammar_point: "以上は", meaning: "because; since; seeing that~" },
  413: { pattern: /いきなり/, grammar_point: "いきなり", meaning: "abruptly; suddenly; all of a sudden" },
  414: { pattern: /(一気に|いっきに)/, grammar_point: "いっきに", meaning: "in one go; without stopping; all at once" },
  415: { pattern: /(一方で|いっぽうで)/, grammar_point: "いっぽうで", meaning: "on one hand; on the other hand; although~" },
  416: { pattern: /いわゆる/, grammar_point: "いわゆる", meaning: "what is called; as it is called; the so-called" },
  417: { pattern: /いよいよ/, grammar_point: "いよいよ", meaning: "at last; finally; beyond doubt" },
  419: { pattern: /かのように/, grammar_point: "かのように", meaning: "as if; just like~" },
  420: { pattern: /かと思ったら/, grammar_point: "かと思ったら", meaning: "just when; no sooner than~" },
  421: { pattern: /か.+ないかのうちに/, grammar_point: "か〜ないかのうちに", meaning: "just as; right after; as soon as~" },
  422: { pattern: /かえって/, grammar_point: "かえって", meaning: "on the contrary; rather; all the more" },
  424: { pattern: /(甲斐|かい)がある/, grammar_point: "甲斐がある", meaning: "it's worth one's efforts to do something" },
  425: { pattern: /かねない/, grammar_point: "かねない", meaning: "(someone) might do something" },
  426: { pattern: /かねる/, grammar_point: "かねる", meaning: "unable to do something; can't do something" },
  427: { pattern: /から(いうと|言うと)/, grammar_point: "からいうと", meaning: "in terms of; from the point of view of~" },
  428: { pattern: /からこそ/, grammar_point: "からこそ", meaning: "precisely because~" },
  429: { pattern: /から(みると|見ると)/, grammar_point: "からみると", meaning: "from the point of view of; by the look of" },
  430: { pattern: /からには/, grammar_point: "からには", meaning: "now that; since; so long as; because~" },
  431: { pattern: /からして/, grammar_point: "からして", meaning: "judging from; based on; since; from; even~" },
  432: { pattern: /から(すると|すれば)/, grammar_point: "からすると・からすれば", meaning: "judging from; considering; by the look of~" },
  433: { pattern: /からといって/, grammar_point: "からといって", meaning: "just because; even if; even though~" },
  434: { pattern: /っこない/, grammar_point: "っこない", meaning: "no chance of; …is definitely not possible" },
  436: { pattern: /ことだから/, grammar_point: "ことだから", meaning: "because; since~" },
  438: { pattern: /ことなく/, grammar_point: "ことなく", meaning: "without doing something even once" },
  440: { pattern: /ことにはならない/, grammar_point: "ことにはならない", meaning: "just because… doesn't mean~" },
  441: { pattern: /くせして/, grammar_point: "くせして", meaning: "although~; despite the fact that~" },
  442: { pattern: /まだしも/, grammar_point: "まだしも", meaning: "rather; better ~" },
  444: { pattern: /ままに/, grammar_point: "ままに", meaning: "as; to do as~" },
  445: { pattern: /(全く|まったく).+(ない|ません)/, grammar_point: "全く〜ない", meaning: "not at all~" },
  446: { pattern: /(もかまわず|も構わず)/, grammar_point: "もかまわず", meaning: "without caring; without worrying about~" },
  447: { pattern: /も当然だ/, grammar_point: "も当然だ", meaning: "it's only natural; no wonder; might as well~" },
  449: { pattern: /ものだ/, grammar_point: "ものだ", meaning: "describe feeling; express memories; state fact" },
  450: { pattern: /ものだから/, grammar_point: "ものだから", meaning: "so; therefore; the reason for something" },
  451: { pattern: /ものではない/, grammar_point: "ものではない", meaning: "shouldn't do something; it's impossible to~" },
  452: { pattern: /ものがある/, grammar_point: "ものがある", meaning: "there is such a thing; to be the case that" },
  453: { pattern: /(ものか|もんか)/, grammar_point: "ものか・もんか", meaning: "as if (something untrue were actually true)" },
  454: { pattern: /ものなら/, grammar_point: "ものなら", meaning: "if I/we could; if [A] is possible then [B]" },
  455: { pattern: /ものの/, grammar_point: "ものの", meaning: "but; although; even though~" },
  456: { pattern: /もっとも/, grammar_point: "もっとも", meaning: "but then; although; though~" },
  457: { pattern: /もう少しで/, grammar_point: "もう少しで", meaning: "almost; nearly; close to~" },
  458: { pattern: /ないではいられない/, grammar_point: "ないではいられない", meaning: "can't help but feel; can't help but do~" },
  459: { pattern: /ないことには.+(ない|ません)/, grammar_point: "ないことには〜ない", meaning: "unless you~" },
  460: { pattern: /なくはない/, grammar_point: "なくはない", meaning: "it's not that; I may (double negative)" },
  461: { pattern: /なくて済む/, grammar_point: "なくて済む", meaning: "get by without doing~" },
  462: { pattern: /(何も|なにも).+(ない|ません)/, grammar_point: "何も〜ない", meaning: "nothing; (not) ~ at all; there's no need to~" },
  464: { pattern: /ねばならない/, grammar_point: "ねばならない", meaning: "have to do; must; should~" },
  465: { pattern: /にあたって/, grammar_point: "にあたって", meaning: "at the time; on the occasion of~" },
  466: { pattern: /にほかならない/, grammar_point: "にほかならない", meaning: "nothing but; none other than~" },
  467: { pattern: /に限らず/, grammar_point: "に限らず", meaning: "not just; not only.. but also~" },
  468: { pattern: /に限る/, grammar_point: "に限る", meaning: "is best; nothing is better than~" },
  469: { pattern: /に限って/, grammar_point: "に限って", meaning: "only; in particular~" },
  470: { pattern: /に(関わらず|かかわらず)/, grammar_point: "に関わらず", meaning: "in spite of; regardless of~" },
  471: { pattern: /に(関わる|かかわる)/, grammar_point: "に関わる", meaning: "to relate to; to have to do with; relating to~" },
  472: { pattern: /に決まっている/, grammar_point: "に決まっている", meaning: "certainly; I'm sure/certain that; it must be" },
  473: { pattern: /に越したことはない/, grammar_point: "に越したことはない", meaning: "it's best that; there's nothing better than~" },
  474: { pattern: /に(応えて|こたえて)/, grammar_point: "に応えて", meaning: "in response to~" },
  475: { pattern: /に加えて/, grammar_point: "に加えて", meaning: "in addition~" },
  476: { pattern: /に基づいて/, grammar_point: "に基づいて", meaning: "based on; on the basis of~" },
  477: { pattern: /に向かって/, grammar_point: "に向かって", meaning: "to face; to go towards; to head to~" },
  478: { pattern: /に応じて/, grammar_point: "に応じて", meaning: "depending on; in accordance with~" },
  479: { pattern: /に際して/, grammar_point: "に際して", meaning: "on the occasion of; at the time of~" },
  480: { pattern: /に(先立ち|さきだち)/, grammar_point: "にさきだち", meaning: "before; prior to~" },
  481: { pattern: /(にせよ|にしろ)(?!.+にしろ)/, grammar_point: "にせよ・にしろ", meaning: "even if; regardless; whether... or" },
  482: { pattern: /にしろ.+にしろ/, grammar_point: "にしろ〜にしろ", meaning: "whether… or~" },
  483: { pattern: /に(したら|すれば)/, grammar_point: "にしたら・にすれば", meaning: "from one's perspective; from the point of" },
  484: { pattern: /にしても.+にしても/, grammar_point: "にしても〜にしても", meaning: "regardless of whether~" },
  485: { pattern: /に沿って/, grammar_point: "に沿って", meaning: "along with; in accordance with" },
  486: { pattern: /に相違ない/, grammar_point: "に相違ない", meaning: "without a doubt; certain; sure" },
  487: { pattern: /に過ぎない/, grammar_point: "に過ぎない", meaning: "no more than; just; merely; only~" },
  488: { pattern: /に(伴って|ともなって)/, grammar_point: "に伴って", meaning: "as; due to; with; along with; following" },
  489: { pattern: /につけ/, grammar_point: "につけ", meaning: "every time; whenever; as; whether" },
  490: { pattern: /につき/, grammar_point: "につき", meaning: "due to; because of; per; each" },
  491: { pattern: /にわたって/, grammar_point: "にわたって", meaning: "throughout; over a period of~" },
  492: { pattern: /にも(関わらず|かかわらず)/, grammar_point: "にも関わらず", meaning: "despite; in spite of; nevertheless; although~" },
  494: { pattern: /のももっともだ/, grammar_point: "のももっともだ", meaning: "no wonder; …is only natural" },
  495: { pattern: /の(下で|もとで)/, grammar_point: "の下で", meaning: "under; with~" },
  496: { pattern: /の上では/, grammar_point: "の上では", meaning: "according to; from the viewpoint of~" },
  497: { pattern: /のみならず/, grammar_point: "のみならず", meaning: "not only; besides; as well as~" },
  500: { pattern: /を契機に/, grammar_point: "を契機に", meaning: "as a good opportunity/chance to; as a result" },
  501: { pattern: /をめぐって/, grammar_point: "をめぐって", meaning: "concerning; in regard to~" },
  502: { pattern: /をもとに/, grammar_point: "をもとに", meaning: "based on; derived from; building on" },
  503: { pattern: /を除いて/, grammar_point: "を除いて", meaning: "except; with the exception of; excluding~" },
  504: { pattern: /を問わず/, grammar_point: "を問わず", meaning: "regardless of; irrespective of; no matter" },
  505: { pattern: /お.+(願う|ねがう)/, grammar_point: "お〜願う", meaning: "please do; could you please…; I ask of you" },
  506: { pattern: /おまけに/, grammar_point: "おまけに", meaning: "to make matters worse; besides; what's" },
  507: { pattern: /(恐らく|おそらく)/, grammar_point: "恐らく", meaning: "perhaps; likely; probably; I dare say~" },
  508: { pattern: /(恐れ|おそれ)がある/, grammar_point: "恐れがある", meaning: "it is feared that; to be in danger of; to be" },
  509: { pattern: /(及び|および)/, grammar_point: "及び", meaning: "and; as well as~" },
  510: { pattern: /ろくに.+(ない|ません)/, grammar_point: "ろくに〜ない", meaning: "not well; not enough; improperly" },
  511: { pattern: /幸いなことに/, grammar_point: "幸いなことに", meaning: "fortunately; luckily; thankfully~" },
  512: { pattern: /せいか/, grammar_point: "せいか", meaning: "perhaps because~" },
  513: { pattern: /せっかく/, grammar_point: "せっかく", meaning: "especially; (thank you for) troubling to" },
  514: { pattern: /せめて/, grammar_point: "せめて", meaning: "at least; at most~" },
  516: { pattern: /次第で/, grammar_point: "次第で", meaning: "depending on; so~" },
  517: { pattern: /次第に/, grammar_point: "次第に", meaning: "gradually (progress into a state)" },
  518: { pattern: /しかも/, grammar_point: "しかも", meaning: "moreover; furthermore; and yet; what's" },
  519: { pattern: /その上/, grammar_point: "その上", meaning: "besides; in addition; furthermore~" },
  520: { pattern: /それなのに/, grammar_point: "それなのに", meaning: "and yet; despite this; but even so~" },
  521: { pattern: /それにしても/, grammar_point: "それにしても", meaning: "nevertheless; at any rate; even so" },
  522: { pattern: /そういえば/, grammar_point: "そういえば", meaning: "come to think of it…; now that you mention" },
  523: { pattern: /そうすると/, grammar_point: "そうすると", meaning: "having done that; if that is done" },
  524: { pattern: /(末に|すえに)/, grammar_point: "末に", meaning: "finally; after; following; at the end" },
  525: { pattern: /少しも.+(ない|ません)/, grammar_point: "少しも〜ない", meaning: "not one bit; not even a little~" },
  526: { pattern: /少なくとも/, grammar_point: "少なくとも", meaning: "at least~" },
  527: { pattern: /(直ちに|ただちに)/, grammar_point: "直ちに", meaning: "at once; immediately; directly; in person" },
  528: { pattern: /たまえ/, grammar_point: "たまえ", meaning: "do~; order somebody to do something" },
  529: { pattern: /てばかりはいられない/, grammar_point: "てばかりはいられない", meaning: "can't keep doing~" },
  530: { pattern: /てでも/, grammar_point: "てでも", meaning: "even if I have to; by all means~" },
  531: { pattern: /て以来/, grammar_point: "て以来", meaning: "since; henceforth~" },
  532: { pattern: /ていては/, grammar_point: "ていては", meaning: "if one keeps doing~" },
  533: { pattern: /てこそ/, grammar_point: "てこそ", meaning: "now that; since (something happened)" },
  534: { pattern: /てまで/, grammar_point: "てまで", meaning: "even; will go far so as to~" },
  535: { pattern: /てならない/, grammar_point: "てならない", meaning: "can't help but; dying to; extremely~" },
  536: { pattern: /てたまらない/, grammar_point: "てたまらない", meaning: "can't help but; dying to; extremely~" },
  537: { pattern: /て当然だ/, grammar_point: "て当然だ", meaning: "natural; as a matter of course" },
  539: { pattern: /てはいられない/, grammar_point: "てはいられない", meaning: "can't afford to; unable to~" },
  540: { pattern: /てはならない/, grammar_point: "てはならない", meaning: "must not; cannot; should not~" },
  541: { pattern: /ては.+ては/, grammar_point: "ては〜ては", meaning: "repetitive situations/actions" },
  542: { pattern: /と同時に/, grammar_point: "と同時に", meaning: "at the same time as; while; simultaneously~" },
  543: { pattern: /といった/, grammar_point: "といった", meaning: "like; such as~" },
  544: { pattern: /というふうに/, grammar_point: "というふうに", meaning: "in such a way that~" },
  545: { pattern: /ということは/, grammar_point: "ということは", meaning: "that is to say; so that means; in other words~" },
  546: { pattern: /というものだ/, grammar_point: "というものだ", meaning: "something like; something called~" },
  547: { pattern: /というものではない/, grammar_point: "というものではない", meaning: "there is no guarantee that…; not necessarily~" },
  548: { pattern: /と考えられる/, grammar_point: "と考えられる", meaning: "one can think that; it is conceivable that" },
  550: { pattern: /とっくに/, grammar_point: "とっくに", meaning: "long ago; already; a long time ago" },
  551: { pattern: /ところだった/, grammar_point: "ところだった", meaning: "was just about to do something" },
  553: { pattern: /ところを(みると|見ると)/, grammar_point: "ところをみると", meaning: "judging from; seeing that~" },
  555: { pattern: /としても/, grammar_point: "としても", meaning: "assuming; even if~" },
  557: { pattern: /つつある/, grammar_point: "つつある", meaning: "to be doing; to be in the process of doing~" },
  559: { pattern: /はもとより/, grammar_point: "はもとより", meaning: "also; let alone; from the beginning" },
  560: { pattern: /はともかく/, grammar_point: "はともかく", meaning: "anyhow; anyway; regardless; in any case" },
  561: { pattern: /わずかに/, grammar_point: "わずかに", meaning: "slightly; only; barely; narrowly~" },
  562: { pattern: /やがて/, grammar_point: "やがて", meaning: "before long; soon; almost; eventually~" },
  563: { pattern: /やら.+やら/, grammar_point: "やら〜やら", meaning: "such things as A and B; A and B and so on~" },
  564: { pattern: /(よほど|よっぽど)/, grammar_point: "よほど・よっぽど", meaning: "very; greatly; much; to a large extent" },
  566: { pattern: /よりほかない/, grammar_point: "よりほかない", meaning: "to have no choice but~" },
  567: { pattern: /ようでは/, grammar_point: "ようでは", meaning: "if~ (bad result)" },
  568: { pattern: /ようではないか/, grammar_point: "ようではないか", meaning: "let's do (something); why don't we~" },
  569: { pattern: /ようか.+まいか/, grammar_point: "ようか〜まいか", meaning: "whether or not; considering options" },
  570: { pattern: /要するに/, grammar_point: "要するに", meaning: "in short; in a word; to sum up" },
  571: { pattern: /ざるを得ない/, grammar_point: "ざるを得ない", meaning: "cannot help (doing); have no choice but to~" },
  572: { pattern: /ずに済む/, grammar_point: "ずに済む", meaning: "get by without doing~" },
};

const MIN_SENTENCE_LENGTH = 8;

/**
 * Detect all JLPT grammar patterns in a sentence.
 * Returns an array of grammar_ids that matched.
 * grammar_id values match the grammar_id column in master_grammar.
 */
export function detect(sentence: string): number[] {
  if (sentence.length < MIN_SENTENCE_LENGTH) return [];
  const matched: number[] = [];
  for (const [idStr, entry] of Object.entries(ALL_PATTERNS)) {
    if (entry.pattern.test(sentence)) {
      matched.push(Number(idStr));
    }
  }
  return matched;
}
