import * as fs from 'fs';
import * as path from 'path';
import * as http from 'http';
import { app, BrowserWindow, ipcMain, globalShortcut, shell } from 'electron';
import { initializeDatabase, closeDatabase } from './database/connection';
import { registerContentHandlers } from './ipc/handlers';
import { registerUserHandlers } from './ipc/userHandlers';
import { registerGrammarHandlers } from './ipc/grammarHandlers';
import { loadSession } from './session';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Disable GPU hardware acceleration to avoid issues on some Linux systems
app.disableHardwareAcceleration();
app.commandLine.appendSwitch('disable-gpu');
app.commandLine.appendSwitch('disable-gpu-sandbox');
app.commandLine.appendSwitch('use-gl', 'swiftshader');

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// if (require('electron-squirrel-startup')) {
//   app.quit();
// }

let mediaServerPort = 0;

/**
 * Start a local HTTP server to serve media files.
 * Custom protocol handlers (protocol.handle) have issues with streaming in Electron;
 * a plain HTTP server on localhost is the most reliable approach.
 */
function startMediaServer(mediaDir: string): Promise<void> {
  return new Promise((resolve) => {
    const server = http.createServer((req, res) => {
      res.setHeader('Access-Control-Allow-Origin', '*');

      try {
        const parsedUrl = new URL('http://localhost' + (req.url ?? '/'));
        const filePath = parsedUrl.searchParams.get('f');

        if (!filePath) {
          res.writeHead(400);
          res.end('Missing file parameter');
          return;
        }

        // Security: only serve files within the media directory
        const resolved = path.resolve(filePath);
        const resolvedDir = path.resolve(mediaDir);
        if (!resolved.startsWith(resolvedDir + path.sep)) {
          console.log('[media-server] Blocked path traversal attempt:', resolved);
          res.writeHead(403);
          res.end('Forbidden');
          return;
        }

        if (!fs.existsSync(resolved)) {
          console.log('[media-server] File not found:', resolved);
          res.writeHead(404);
          res.end('Not found');
          return;
        }

        const stat = fs.statSync(resolved);
        const ext = path.extname(resolved).toLowerCase();
        const mimeType = ext === '.mp4' ? 'video/mp4'
          : ext === '.mp3' ? 'audio/mpeg'
          : ext === '.m4a' ? 'audio/mp4'
          : ext === '.webm' ? 'video/webm'
          : ext === '.vtt' ? 'text/vtt'
          : 'application/octet-stream';

        const range = req.headers['range'];
        if (range) {
          const parts = range.replace(/bytes=/, '').split('-');
          const start = parseInt(parts[0], 10);
          const end = parts[1] ? parseInt(parts[1], 10) : stat.size - 1;

          res.writeHead(206, {
            'Content-Type': mimeType,
            'Content-Range': `bytes ${start}-${end}/${stat.size}`,
            'Content-Length': String(end - start + 1),
            'Accept-Ranges': 'bytes',
          });
          fs.createReadStream(resolved, { start, end }).pipe(res);
        } else {
          res.writeHead(200, {
            'Content-Type': mimeType,
            'Content-Length': String(stat.size),
            'Accept-Ranges': 'bytes',
          });
          fs.createReadStream(resolved).pipe(res);
        }
      } catch (err) {
        console.error('[media-server] Error:', err);
        if (!res.headersSent) {
          res.writeHead(500);
          res.end('Internal error');
        }
      }
    });

    server.listen(0, '127.0.0.1', () => {
      const addr = server.address() as { address: string; port: number };
      mediaServerPort = addr.port;
      console.log('[media-server] Listening on port', mediaServerPort);
      resolve();
    });
  });
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  // Initialize database and run migrations before anything else
  try {
    initializeDatabase();
    console.log('Database initialized successfully');
  } catch (error) {
    console.error('Failed to initialize database:', error);
  }

  // Restore the last signed-in user from disk before IPC handlers register
  loadSession();

  // Start media server before the window opens so the port is ready immediately
  const mediaDir = path.join(app.getPath('userData'), 'media');
  await startMediaServer(mediaDir);

  registerContentHandlers();
  registerUserHandlers();
  registerGrammarHandlers();

  ipcMain.handle('shell:openExternal', (_event, url: string) => shell.openExternal(url));
  ipcMain.handle('media:getPort', () => mediaServerPort);
  createWindow();

  // Register Ctrl+Shift+I to toggle DevTools
  globalShortcut.register('CommandOrControl+Shift+I', () => {
    const win = BrowserWindow.getFocusedWindow();
    // if (win) {
    //   win.webContents.toggleDevTools();
    // }
  });
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('will-quit', () => {
  closeDatabase();
  globalShortcut.unregisterAll();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
